// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpartaIMS_Database.Data;

namespace SpartaIMSWebsite.Migrations
{
    [DbContext(typeof(SpartaIMSDbContext))]
    [Migration("20190328165421_InitialSpartaDbMigration")]
    partial class InitialSpartaDbMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpartaIMS_Database.Models.Cohort", b =>
                {
                    b.Property<int>("CohortID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CohortName");

                    b.Property<int>("SpecID");

                    b.HasKey("CohortID");

                    b.HasIndex("SpecID");

                    b.ToTable("Cohorts");
                });

            modelBuilder.Entity("SpartaIMS_Database.Models.JobRole", b =>
                {
                    b.Property<int>("JobRoleID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JobRoleName");

                    b.HasKey("JobRoleID");

                    b.ToTable("JobRoles");
                });

            modelBuilder.Entity("SpartaIMS_Database.Models.SpartanUser", b =>
                {
                    b.Property<int>("SpartanID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CohortID");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("FullName");

                    b.Property<int>("JobRoleID");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password");

                    b.HasKey("SpartanID");

                    b.HasIndex("CohortID");

                    b.HasIndex("JobRoleID");

                    b.ToTable("SpartanUsers");
                });

            modelBuilder.Entity("SpartaIMS_Database.Models.Specialisation", b =>
                {
                    b.Property<int>("SpecID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SpecName");

                    b.HasKey("SpecID");

                    b.ToTable("Specialisations");
                });

            modelBuilder.Entity("SpartaIMS_Database.Models.Cohort", b =>
                {
                    b.HasOne("SpartaIMS_Database.Models.Specialisation", "Specialisations")
                        .WithMany("Cohorts")
                        .HasForeignKey("SpecID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SpartaIMS_Database.Models.SpartanUser", b =>
                {
                    b.HasOne("SpartaIMS_Database.Models.Cohort", "Cohort")
                        .WithMany("SpartanUsers")
                        .HasForeignKey("CohortID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SpartaIMS_Database.Models.JobRole", "JobRole")
                        .WithMany("SpartanUsers")
                        .HasForeignKey("JobRoleID")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
